bundled_packages_dir: packages
data_dir: data
description: Text to image
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  pretty_name: Deepfloyd XL
  tags:
  - image-generation
model_module_dir: model
model_name: Deepfloyd XL
model_type: custom
python_version: py39
requirements:
- diffusers
- transformers
- torch
- scipy
- accelerate
- pillow
- bitsandbytes
- sentencepiece
- huggingface_hub
resources:
  cpu: "3"
  memory: 14Gi
  use_gpu: true
  accelerator: A10G
secrets:
  hf_api_key: "ENTER HF API KEY HERE"
system_packages: []
spec_version: 2.0
